UT Changes Stage4
ResearchCollectionsAndPreservation/Phase4-SCSB-Core pull request #157
Opened 2021-10-04 07:45 UTC by JancyRoachR

2021-10-07 06:09 UTC, rajeshbabuk requested changes
Rename logback xml file to its original name

2021-10-07 06:20 UTC, JancyRoachR commented
> Rename logback xml file to its original name

DONE.

2021-10-07 06:22 UTC, rajeshbabuk approved these changes

2021-10-12 06:05 UTC, srinduri04 approved these changes
Approved

2021-10-12 06:05 UTC, merged